dbt_project:
  target: local
  outputs:
    local:
      type: duckdb
      path: "/Users/sspaeti/Simon/Sync/1 Areas/Finance/Bank/Kontoauszüge/_export/_Transaktionen_Export/Test-2024/example.duckdb"
      schema: dbt_schema
